baseurl = "https://humbleui.github.io"
RelativeURLs=true
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10

# Multilingual
defaultContentLanguage = "en"
disableLanguages = []
# defaultContentLanguageInSubdir = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
section = ["HTML", "RSS", "SITEMAP"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediaType = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5


[permalinks]
  docs = "docs/:sections[1:]/:title/"
# docs = "/docs/1.0/:sections[1:]/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"
    max = ""
  [[module.mounts]]
    source = "node_modules/@hyas/doks/archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/assets"
    target = "assets"
#  [[module.mounts]]
#    source = "node_modules/@hyas/doks/content"
#    target = "content"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/data"
    target = "data"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/layouts"
    target = "layouts"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "node_modules/katex"
    target = "assets/js/vendor/katex"
  [[module.mounts]]
    source = "node_modules/mermaid"
    target = "assets/js/vendor/mermaid"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
#  [[module.mounts]]
#    source = "content"
#    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "data"
    target = "data"
