name: Rebuild Linux Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'

jobs:
  deploy_ghpage:
    name: Deploy JWM website
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: |
          cd website
          npm install --only prod
          hugo --gc --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
